openapi: 3.0.0

info:
  title: Tamer Travel API Documentation
  description: Welcome to the API documentation for Tamer Travel.
  contact:
    name: Tamer
    email: "tameryoussef2@gmail.com"
    url: "https://github.com/tamer-youssef"
  version: 1.0.0

servers:
  - url: http://tamertravel.com/v1
  - url: http://tamertravel2.com/v1

paths:
  /countries:
    get:
      tags:
        - User
      summary: Get a list of countries by location or budget, and travel date.
      parameters:
        - name: Name
          in: query
          description: Name of the country
          schema:
            type: string
            
        - name: Budget
          in: query
          description: Budget for the trip
          schema:
            type: integer
            
        - name: Arrival Date
          in: query
          description: Arrival date for the trip
          required: true
          schema:
            type: string
            format: date
            
        - name: Departure Date
          in: query
          description: Departure for the trip
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
    post:
      tags:
        - Admin
      summary: Add a new country
      requestBody:
        description: Country object to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '201':
          description: Country added successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error

    put:
      tags:
        - Admin
      summary: Update an existing country
      parameters:
        - name: Name
          in: query
          description: Name of the country to update
          required: true
          schema:
            type: string
      requestBody:
          description: Updated country information
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
      responses:
        '200':
          description: Country updated successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error

    delete:
      tags:
        - Admin
      summary: Remove a country
      parameters:
        - name: Name
          in: query
          description: Name of the country to remove
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Country removed successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error

# components:
#   schemas:
#     Country:
#       type: object
#       properties:
#         name:
#           type: string
#         capital:
#           type: string
#         population:
#           type: integer
#         currency:
#           type: string
#         language:
#           type: string
#         budget:
#           type: integer

components:
  schemas:
    Country:
      type: object
      properties:
          Name:
            type: string
            example: Egypt
          Capital:
            type: string
            example: Cairo
          Continent:
            type: string
            example: Africa
          Budget:
            type: integer
            example: 5000

tags:
  - name: User
    description: These endpoints are accessible by the user.
    
  - name: Admin
    description: These endpoints are accessible by the admin.

